---
- hosts: all
  become: yes
  tasks:
  - name: I want to install webserver
    apt:
     name: {{ubuntuwebpackage}}
     state: present
    when: ansible_os_family=="Debian"
 
  - name: I want to install webserver
    yum:
     name: {{redhatwebpackage}}
     state: present 
    when: ansible_os_family=="RedHat"

  - name: I want to start the server
    service:
     name: {{redhatwebpackage}}
     state: started
    when: ansible_os_family=="RedHat"